import { Template } from './types';

// Категория "AI" - 30 шаблонов с функциями генерации контента
export const aiTemplates: Template[] = [
  {
    id: 'ai-content-generator',
    name: 'AI Content Studio',
    category: 'AI',
    description: 'AI-платформа для генерации контента с автопубликацией',
    thumbnail: '🤖',
    colors: { primary: '#6366f1', secondary: '#8b5cf6', accent: '#06b6d4', background: '#0f172a', text: '#f8fafc' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Content Studio', subtitle: 'Генерация статей, постов и видео с помощью AI. Автоматическая публикация по расписанию.', ctaText: 'Начать бесплатно', ctaSecondary: 'Демо' } },
      { id: 'categories', type: 'categories', editable: true, content: { title: 'AI Инструменты', subtitle: 'Генерация контента', items: [{ icon: '📝', name: 'Статьи', count: 'Авто-генерация' }, { icon: '🎥', name: 'Видео', count: 'AI-монтаж' }, { icon: '🎵', name: 'Музыка', count: 'Композиции' }, { icon: '🖼️', name: 'Изображения', count: 'Генерация' }, { icon: '🎙️', name: 'Голос', count: 'Синтез речи' }, { icon: '📱', name: 'Посты', count: 'Авто-публикация' }] } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Выберите план', plans: [{ name: 'Стартер', price: '990', period: '/мес', features: ['100 генераций/мес', '5 статей', 'Базовая поддержка'], highlighted: false }, { name: 'Про', price: '2990', period: '/мес', features: ['1000 генераций/мес', 'Безлимит статей', 'Авто-публикация', 'API доступ'], highlighted: true }, { name: 'Бизнес', price: '9990', period: '/мес', features: ['Безлимит', 'Все инструменты', 'Приоритет', 'On-premise'], highlighted: false }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Content Studio', description: 'AI платформа для создания контента', links: [] } },
    ],
  },
  {
    id: 'ai-article-writer',
    name: 'AI Article Writer',
    category: 'AI',
    description: 'Автоматическая генерация и публикация статей',
    thumbnail: '✍️',
    colors: { primary: '#059669', secondary: '#10b981', accent: '#f59e0b', background: '#f0fdf4', text: '#064e3b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Article Writer', subtitle: 'Генерация SEO-оптимизированных статей с автоматической публикацией на ваш сайт', ctaText: 'Попробовать', ctaSecondary: 'Примеры' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Автоматическая публикация', plans: [{ name: 'Базовый', price: '1990', period: '/мес', features: ['10 статей/мес', 'Авто-публикация', 'SEO оптимизация'], highlighted: false }, { name: 'Про', price: '4990', period: '/мес', features: ['50 статей/мес', 'Расписание публикаций', 'Мульти-платформа'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Article Writer', description: 'Генератор статей', links: [] } },
    ],
  },
  {
    id: 'ai-video-generator',
    name: 'AI Video Creator',
    category: 'AI',
    description: 'Генерация видео с AI-монтажом',
    thumbnail: '🎬',
    colors: { primary: '#dc2626', secondary: '#ef4444', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Video Creator', subtitle: 'Создание видео из текста с AI-монтажом и автопубликацией', ctaText: 'Создать видео', ctaSecondary: 'Примеры' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Видео генерация', plans: [{ name: 'Стартер', price: '2990', period: '/мес', features: ['5 видео/мес', 'HD качество', 'Базовые шаблоны'], highlighted: false }, { name: 'Про', price: '7990', period: '/мес', features: ['30 видео/мес', '4K качество', 'Все шаблоны', 'Авто-публикация'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Video Creator', description: 'AI видео', links: [] } },
    ],
  },
  {
    id: 'ai-voice-synthesis',
    name: 'AI Voice Studio',
    category: 'AI',
    description: 'Синтез речи и клонирование голоса',
    thumbnail: '🎙️',
    colors: { primary: '#7c3aed', secondary: '#a855f7', accent: '#ec4899', background: '#faf5ff', text: '#5b21b6' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Voice Studio', subtitle: 'Синтез речи на 50+ языках с клонированием голоса', ctaText: 'Попробовать', ctaSecondary: 'Демо' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Голосовой синтез', plans: [{ name: 'Базовый', price: '990', period: '/мес', features: ['10000 символов', '5 голосов', 'MP3'], highlighted: false }, { name: 'Про', price: '2990', period: '/мес', features: ['100000 символов', 'Все голоса', 'WAV/MP3', 'Клонирование'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Voice Studio', description: 'Синтез речи', links: [] } },
    ],
  },
  {
    id: 'ai-music-generator',
    name: 'AI Music Lab',
    category: 'AI',
    description: 'Генерация музыки и песен',
    thumbnail: '🎵',
    colors: { primary: '#be185d', secondary: '#ec4899', accent: '#fbbf24', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Music Lab', subtitle: 'Создание оригинальной музыки и песен с помощью AI', ctaText: 'Создать трек', ctaSecondary: 'Библиотека' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Генерация музыки', plans: [{ name: 'Базовый', price: '1490', period: '/мес', features: ['10 треков/мес', 'MP3', 'Коммерческая лицензия'], highlighted: false }, { name: 'Про', price: '3990', period: '/мес', features: ['50 треков/мес', 'WAV/MP3', 'Все стили', 'Без лицензий'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Music Lab', description: 'AI музыка', links: [] } },
    ],
  },
  {
    id: 'ai-image-generator',
    name: 'AI Image Studio',
    category: 'AI',
    description: 'Генерация изображений по тексту',
    thumbnail: '🎨',
    colors: { primary: '#0891b2', secondary: '#06b6d4', accent: '#f97316', background: '#ecfeff', text: '#164e63' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Image Studio', subtitle: 'Генерация уникальных изображений по текстовому описанию', ctaText: 'Создать', ctaSecondary: 'Галерея' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Генерация изображений', plans: [{ name: 'Базовый', price: '790', period: '/мес', features: ['100 изображений', 'SD качество', 'Коммерческое использование'], highlighted: false }, { name: 'Про', price: '1990', period: '/мес', features: ['1000 изображений', 'HD качество', 'Все стили', 'API'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Image Studio', description: 'AI изображения', links: [] } },
    ],
  },
  {
    id: 'ai-social-media',
    name: 'AI Social Manager',
    category: 'AI',
    description: 'Автоматическое управление соцсетями',
    thumbnail: '📱',
    colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#10b981', background: '#eff6ff', text: '#1e3a8a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Social Manager', subtitle: 'Автоматическое создание и публикация постов во всех соцсетях', ctaText: 'Начать', ctaSecondary: 'Демо' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Управление соцсетями', plans: [{ name: 'Базовый', price: '1990', period: '/мес', features: ['3 соцсети', '30 постов/мес', 'Авто-публикация'], highlighted: false }, { name: 'Про', price: '4990', period: '/мес', features: ['Все соцсети', 'Безлимит постов', 'Аналитика', 'AI контент'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Social Manager', description: 'AI соцсети', links: [] } },
    ],
  },
  {
    id: 'ai-blog-automation',
    name: 'AI Blog Automation',
    category: 'AI',
    description: 'Полная автоматизация блога',
    thumbnail: '📝',
    colors: { primary: '#7c2d12', secondary: '#ea580c', accent: '#16a34a', background: '#fff7ed', text: '#7c2d12' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Blog Automation', subtitle: 'Автоматическое создание, оптимизация и публикация постов в блоге', ctaText: 'Настроить', ctaSecondary: 'Примеры' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Автоматизация блога', plans: [{ name: 'Стартер', price: '2990', period: '/мес', features: ['10 постов/мес', 'Авто-SEO', '1 блог'], highlighted: false }, { name: 'Про', price: '7990', period: '/мес', features: ['50 постов/мес', 'Расписание', '5 блогов', 'Аналитика'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Blog Automation', description: 'AI блог', links: [] } },
    ],
  },
  {
    id: 'ai-youtube',
    name: 'AI YouTube Studio',
    category: 'AI',
    description: 'Автоматизация YouTube канала',
    thumbnail: '📺',
    colors: { primary: '#dc2626', secondary: '#ef4444', accent: '#ffffff', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI YouTube Studio', subtitle: 'Автоматическое создание и публикация видео на YouTube', ctaText: 'Создать канал', ctaSecondary: 'Демо' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'YouTube автоматизация', plans: [{ name: 'Базовый', price: '3990', period: '/мес', features: ['5 видео/мес', 'Авто-загрузка', 'SEO оптимизация'], highlighted: false }, { name: 'Про', price: '9990', period: '/мес', features: ['30 видео/мес', 'Расписание', 'Монетизация', 'Аналитика'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI YouTube Studio', description: 'AI YouTube', links: [] } },
    ],
  },
  {
    id: 'ai-podcast',
    name: 'AI Podcast Creator',
    category: 'AI',
    description: 'Создание подкастов с AI',
    thumbnail: '🎧',
    colors: { primary: '#7c3aed', secondary: '#a855f7', accent: '#f59e0b', background: '#faf5ff', text: '#5b21b6' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Podcast Creator', subtitle: 'Автоматическое создание подкастов с AI-ведущим', ctaText: 'Создать подкаст', ctaSecondary: 'Примеры' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Подкасты', plans: [{ name: 'Базовый', price: '1990', period: '/мес', features: ['4 эпизода/мес', 'AI голос', 'Хостинг'], highlighted: false }, { name: 'Про', price: '4990', period: '/мес', features: ['20 эпизодов/мес', 'Все голоса', 'Расписание', 'Дистрибуция'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Podcast Creator', description: 'AI подкасты', links: [] } },
    ],
  },
  {
    id: 'ai-newsletter',
    name: 'AI Newsletter',
    category: 'AI',
    description: 'Автоматические email-рассылки',
    thumbnail: '📧',
    colors: { primary: '#059669', secondary: '#10b981', accent: '#f59e0b', background: '#f0fdf4', text: '#064e3b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Newsletter', subtitle: 'Автоматическое создание и отправка email-рассылок', ctaText: 'Настроить', ctaSecondary: 'Шаблоны' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Email рассылки', plans: [{ name: 'Стартер', price: '990', period: '/мес', features: ['1000 подписчиков', '4 рассылки/мес', 'AI контент'], highlighted: false }, { name: 'Про', price: '2990', period: '/мес', features: ['10000 подписчиков', 'Безлимит рассылок', 'A/B тесты', 'Аналитика'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Newsletter', description: 'AI рассылки', links: [] } },
    ],
  },
  {
    id: 'ai-copywriting',
    name: 'AI Copywriter',
    category: 'AI',
    description: 'AI-копирайтер для маркетинга',
    thumbnail: '💡',
    colors: { primary: '#f59e0b', secondary: '#fbbf24', accent: '#dc2626', background: '#fffbeb', text: '#78350f' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Copywriter', subtitle: 'Генерация маркетинговых текстов и рекламы', ctaText: 'Создать текст', ctaSecondary: 'Примеры' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Копирайтинг', plans: [{ name: 'Базовый', price: '1490', period: '/мес', features: ['50 текстов/мес', 'Все форматы', 'Коммерческая лицензия'], highlighted: false }, { name: 'Про', price: '3990', period: '/мес', features: ['Безлимит', 'API доступ', 'Бренд-голос', 'A/B тесты'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Copywriter', description: 'AI копирайтинг', links: [] } },
    ],
  },
  {
    id: 'ai-translation',
    name: 'AI Translator',
    category: 'AI',
    description: 'AI-переводчик с сохранением стиля',
    thumbnail: '🌍',
    colors: { primary: '#0891b2', secondary: '#06b6d4', accent: '#10b981', background: '#ecfeff', text: '#164e63' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Translator', subtitle: 'Перевод текстов на 100+ языков с сохранением стиля', ctaText: 'Перевести', ctaSecondary: 'Языки' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Перевод', plans: [{ name: 'Базовый', price: '790', period: '/мес', features: ['100000 символов', '50 языков', 'Документы'], highlighted: false }, { name: 'Про', price: '1990', period: '/мес', features: ['Безлимит', '100+ языков', 'API', 'Стиль бренда'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Translator', description: 'AI перевод', links: [] } },
    ],
  },
  {
    id: 'ai-seo',
    name: 'AI SEO Optimizer',
    category: 'AI',
    description: 'AI-оптимизация для поисковых систем',
    thumbnail: '🔍',
    colors: { primary: '#16a34a', secondary: '#22c55e', accent: '#f59e0b', background: '#f0fdf4', text: '#14532d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI SEO Optimizer', subtitle: 'Автоматическая SEO-оптимизация контента', ctaText: 'Оптимизировать', ctaSecondary: 'Аудит' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'SEO оптимизация', plans: [{ name: 'Базовый', price: '1990', period: '/мес', features: ['10 страниц', 'Базовый аудит', 'Рекомендации'], highlighted: false }, { name: 'Про', price: '4990', period: '/мес', features: ['100 страниц', 'Полный аудит', 'Авто-оптимизация', 'Мониторинг'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI SEO Optimizer', description: 'AI SEO', links: [] } },
    ],
  },
  {
    id: 'ai-chatbot',
    name: 'AI Chatbot Builder',
    category: 'AI',
    description: 'Создание AI-чатботов',
    thumbnail: '💬',
    colors: { primary: '#6366f1', secondary: '#8b5cf6', accent: '#ec4899', background: '#f8fafc', text: '#0f172a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Chatbot Builder', subtitle: 'Создание умных чатботов без программирования', ctaText: 'Создать бота', ctaSecondary: 'Шаблоны' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Чатботы', plans: [{ name: 'Стартер', price: '1490', period: '/мес', features: ['1 бот', '1000 сообщений', 'Базовые интеграции'], highlighted: false }, { name: 'Про', price: '3990', period: '/мес', features: ['10 ботов', 'Безлимит сообщений', 'Все интеграции', 'Аналитика'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Chatbot Builder', description: 'AI чатботы', links: [] } },
    ],
  },
  {
    id: 'ai-data-analysis',
    name: 'AI Data Analyst',
    category: 'AI',
    description: 'AI-анализ данных',
    thumbnail: '📊',
    colors: { primary: '#0c4a6e', secondary: '#0284c7', accent: '#06b6d4', background: '#f0f9ff', text: '#0c4a6e' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Data Analyst', subtitle: 'Автоматический анализ данных и построение прогнозов', ctaText: 'Анализировать', ctaSecondary: 'Демо' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Анализ данных', plans: [{ name: 'Базовый', price: '2990', period: '/мес', features: ['1GB данных', 'Базовые отчёты', '5 моделей'], highlighted: false }, { name: 'Про', price: '7990', period: '/мес', features: ['100GB данных', 'Все отчёты', 'Безлимит моделей', 'API'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Data Analyst', description: 'AI аналитика', links: [] } },
    ],
  },
  {
    id: 'ai-code-assistant',
    name: 'AI Code Assistant',
    category: 'AI',
    description: 'AI-помощник для разработчиков',
    thumbnail: '💻',
    colors: { primary: '#1e293b', secondary: '#475569', accent: '#22d3ee', background: '#f8fafc', text: '#0f172a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Code Assistant', subtitle: 'AI-помощник для написания и ревью кода', ctaText: 'Установить', ctaSecondary: 'Документация' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'AI для кода', plans: [{ name: 'Individual', price: '990', period: '/мес', features: ['Автодополнение', '50 языков', 'Базовое ревью'], highlighted: false }, { name: 'Team', price: '2990', period: '/мес', features: ['Всё из Individual', 'Командное ревью', 'Приоритет', 'Поддержка'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Code Assistant', description: 'AI код', links: [] } },
    ],
  },
  {
    id: 'ai-design',
    name: 'AI Design Studio',
    category: 'AI',
    description: 'AI-дизайн интерфейсов',
    thumbnail: '🎨',
    colors: { primary: '#be185d', secondary: '#ec4899', accent: '#fbbf24', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Design Studio', subtitle: 'Автоматическое создание UI/UX дизайнов', ctaText: 'Создать дизайн', ctaSecondary: 'Примеры' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'AI дизайн', plans: [{ name: 'Базовый', price: '1990', period: '/мес', features: ['10 дизайнов', 'Базовые шаблоны', 'PNG экспорт'], highlighted: false }, { name: 'Про', price: '4990', period: '/мес', features: ['Безлимит', 'Все шаблоны', 'Figma экспорт', 'Компоненты'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Design Studio', description: 'AI дизайн', links: [] } },
    ],
  },
  {
    id: 'ai-marketing',
    name: 'AI Marketing Suite',
    category: 'AI',
    description: 'Комплексный AI-маркетинг',
    thumbnail: '📈',
    colors: { primary: '#059669', secondary: '#10b981', accent: '#f59e0b', background: '#f0fdf4', text: '#064e3b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Marketing Suite', subtitle: 'Полный набор AI-инструментов для маркетинга', ctaText: 'Начать', ctaSecondary: 'Демо' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'AI маркетинг', plans: [{ name: 'Стартер', price: '3990', period: '/мес', features: ['5 инструментов', 'Базовая аналитика', 'Email поддержка'], highlighted: false }, { name: 'Про', price: '9990', period: '/мес', features: ['Все инструменты', 'Продвинутая аналитика', 'API', 'Приоритет'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Marketing Suite', description: 'AI маркетинг', links: [] } },
    ],
  },
  {
    id: 'ai-customer-service',
    name: 'AI Customer Service',
    category: 'AI',
    description: 'AI-служба поддержки клиентов',
    thumbnail: '🎧',
    colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#10b981', background: '#eff6ff', text: '#1e3a8a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Customer Service', subtitle: 'Автоматическая поддержка клиентов 24/7', ctaText: 'Подключить', ctaSecondary: 'Демо' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'AI поддержка', plans: [{ name: 'Базовый', price: '2990', period: '/мес', features: ['1000 тикетов', 'Чат-бот', 'Email'], highlighted: false }, { name: 'Про', price: '7990', period: '/мес', features: ['Безлимит тикетов', 'Все каналы', 'Интеграции', 'Аналитика'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Customer Service', description: 'AI поддержка', links: [] } },
    ],
  },
  {
    id: 'ai-research',
    name: 'AI Research Assistant',
    category: 'AI',
    description: 'AI-помощник для исследований',
    thumbnail: '🔬',
    colors: { primary: '#7c3aed', secondary: '#a855f7', accent: '#06b6d4', background: '#faf5ff', text: '#5b21b6' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Research Assistant', subtitle: 'Автоматизация научных исследований и анализа', ctaText: 'Начать', ctaSecondary: 'Примеры' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'AI исследования', plans: [{ name: 'Академический', price: '1990', period: '/мес', features: ['Базовый поиск', '50 документов', 'Цитирование'], highlighted: false }, { name: 'Профессиональный', price: '4990', period: '/мес', features: ['Полный доступ', 'Безлимит', 'API', 'Командная работа'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Research Assistant', description: 'AI исследования', links: [] } },
    ],
  },
  {
    id: 'ai-education',
    name: 'AI Education Platform',
    category: 'AI',
    description: 'AI-платформа для образования',
    thumbnail: '🎓',
    colors: { primary: '#4f46e5', secondary: '#6366f1', accent: '#10b981', background: '#eef2ff', text: '#3730a3' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Education Platform', subtitle: 'Персонализированное обучение с AI', ctaText: 'Начать обучение', ctaSecondary: 'Курсы' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'AI образование', plans: [{ name: 'Студент', price: '490', period: '/мес', features: ['5 курсов', 'AI-тьютор', 'Сертификаты'], highlighted: false }, { name: 'Про', price: '1490', period: '/мес', features: ['Все курсы', 'Персональный план', 'Менторство', 'API'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Education Platform', description: 'AI образование', links: [] } },
    ],
  },
  {
    id: 'ai-healthcare',
    name: 'AI Healthcare',
    category: 'AI',
    description: 'AI для здравоохранения',
    thumbnail: '🏥',
    colors: { primary: '#0891b2', secondary: '#06b6d4', accent: '#10b981', background: '#ecfeff', text: '#164e63' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Healthcare', subtitle: 'AI-решения для медицины и здоровья', ctaText: 'Узнать больше', ctaSecondary: 'Демо' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'AI медицина', plans: [{ name: 'Клиника', price: '9990', period: '/мес', features: ['Диагностика', 'Аналитика', '5 пользователей'], highlighted: false }, { name: 'Больница', price: '29990', period: '/мес', features: ['Все функции', 'Безлимит', 'Интеграции', 'Поддержка'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Healthcare', description: 'AI медицина', links: [] } },
    ],
  },
  {
    id: 'ai-finance',
    name: 'AI Finance',
    category: 'AI',
    description: 'AI для финансов и инвестиций',
    thumbnail: '💰',
    colors: { primary: '#16a34a', secondary: '#22c55e', accent: '#fbbf24', background: '#f0fdf4', text: '#14532d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Finance', subtitle: 'AI-анализ финансовых данных и прогнозирование', ctaText: 'Начать', ctaSecondary: 'Демо' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'AI финансы', plans: [{ name: 'Трейдер', price: '2990', period: '/мес', features: ['Базовый анализ', '10 стратегий', 'Уведомления'], highlighted: false }, { name: 'Про', price: '7990', period: '/мес', features: ['Полный анализ', 'Безлимит стратегий', 'API', 'Приоритет'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Finance', description: 'AI финансы', links: [] } },
    ],
  },
  {
    id: 'ai-legal',
    name: 'AI Legal Assistant',
    category: 'AI',
    description: 'AI-помощник для юристов',
    thumbnail: '⚖️',
    colors: { primary: '#1c1917', secondary: '#44403c', accent: '#b91c1c', background: '#fafaf9', text: '#1c1917' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Legal Assistant', subtitle: 'Автоматизация юридической работы с AI', ctaText: 'Попробовать', ctaSecondary: 'Демо' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'AI юриспруденция', plans: [{ name: 'Юрист', price: '3990', period: '/мес', features: ['Анализ документов', '50 документов/мес', 'Шаблоны'], highlighted: false }, { name: 'Фирма', price: '9990', period: '/мес', features: ['Безлимит', 'Команда', 'Интеграции', 'Поддержка'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Legal Assistant', description: 'AI право', links: [] } },
    ],
  },
  {
    id: 'ai-real-estate',
    name: 'AI Real Estate',
    category: 'AI',
    description: 'AI для недвижимости',
    thumbnail: '🏠',
    colors: { primary: '#059669', secondary: '#10b981', accent: '#f59e0b', background: '#f0fdf4', text: '#064e3b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Real Estate', subtitle: 'AI-анализ рынка недвижимости', ctaText: 'Анализировать', ctaSecondary: 'Демо' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'AI недвижимость', plans: [{ name: 'Агент', price: '2990', period: '/мес', features: ['Анализ 100 объектов', 'Прогнозы', 'Отчёты'], highlighted: false }, { name: 'Компания', price: '7990', period: '/мес', features: ['Безлимит', 'API', 'Команда', 'Интеграции'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Real Estate', description: 'AI недвижимость', links: [] } },
    ],
  },
  {
    id: 'ai-travel',
    name: 'AI Travel Planner',
    category: 'AI',
    description: 'AI-планировщик путешествий',
    thumbnail: '✈️',
    colors: { primary: '#0891b2', secondary: '#06b6d4', accent: '#f97316', background: '#ecfeff', text: '#164e63' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Travel Planner', subtitle: 'Персонализированные путешествия с AI', ctaText: 'Спланировать', ctaSecondary: 'Примеры' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'AI путешествия', plans: [{ name: 'Путешественник', price: '490', period: '/мес', features: ['3 плана/мес', 'Базовые рекомендации', 'Карты'], highlighted: false }, { name: 'Про', price: '1490', period: '/мес', features: ['Безлимит планов', 'AI гид', 'Бронирование', 'Поддержка'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Travel Planner', description: 'AI путешествия', links: [] } },
    ],
  },
  {
    id: 'ai-ecommerce',
    name: 'AI E-commerce',
    category: 'AI',
    description: 'AI для электронной коммерции',
    thumbnail: '🛒',
    colors: { primary: '#7c3aed', secondary: '#a855f7', accent: '#ec4899', background: '#faf5ff', text: '#5b21b6' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI E-commerce', subtitle: 'AI-оптимизация интернет-магазинов', ctaText: 'Оптимизировать', ctaSecondary: 'Демо' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'AI e-commerce', plans: [{ name: 'Магазин', price: '3990', period: '/мес', features: ['AI рекомендации', 'Персонализация', 'Аналитика'], highlighted: false }, { name: 'Маркетплейс', price: '9990', period: '/мес', features: ['Все функции', 'API', 'Безлимит', 'Поддержка'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI E-commerce', description: 'AI e-commerce', links: [] } },
    ],
  },
  {
    id: 'ai-gaming',
    name: 'AI Gaming Studio',
    category: 'AI',
    description: 'AI для разработки игр',
    thumbnail: '🎮',
    colors: { primary: '#7c3aed', secondary: '#a855f7', accent: '#22d3ee', background: '#faf5ff', text: '#5b21b6' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Gaming Studio', subtitle: 'AI-инструменты для создания игр', ctaText: 'Начать', ctaSecondary: 'Документация' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'AI геймдев', plans: [{ name: 'Инди', price: '1990', period: '/мес', features: ['AI ассеты', 'Генерация уровней', 'Базовые инструменты'], highlighted: false }, { name: 'Студия', price: '7990', period: '/мес', features: ['Все инструменты', 'API', 'Команда', 'Поддержка'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Gaming Studio', description: 'AI игры', links: [] } },
    ],
  },
  {
    id: 'ai-automation',
    name: 'AI Automation Hub',
    category: 'AI',
    description: 'Платформа AI-автоматизации',
    thumbnail: '⚙️',
    colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#10b981', background: '#eff6ff', text: '#1e3a8a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Automation Hub', subtitle: 'Автоматизация бизнес-процессов с помощью AI', ctaText: 'Автоматизировать', ctaSecondary: 'Шаблоны' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'AI автоматизация', plans: [{ name: 'Стартер', price: '2990', period: '/мес', features: ['10 автоматизаций', 'Базовые интеграции', '1000 запусков'], highlighted: false }, { name: 'Бизнес', price: '9990', period: '/мес', features: ['Безлимит', 'Все интеграции', 'API', 'Приоритет'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Automation Hub', description: 'AI автоматизация', links: [] } },
    ],
  },
];
