import { Template } from './types';

// Категория "Блогеры" - 30 шаблонов
export const bloggersTemplates: Template[] = [
  {
    id: 'blogger-personal',
    name: 'Personal Blog',
    category: 'Блогеры',
    description: 'Персональный блог с автоматической публикацией',
    thumbnail: '📝',
    colors: { primary: '#6366f1', secondary: '#8b5cf6', accent: '#ec4899', background: '#f8fafc', text: '#0f172a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Мой Блог', subtitle: 'Мысли, идеи и истории', ctaText: 'Читать', ctaSecondary: 'Подписаться' } },
      { id: 'categories', type: 'categories', editable: true, content: { title: 'Категории', subtitle: 'Темы блога', items: [{ icon: '💡', name: 'Идеи', count: '50+' }, { icon: '📚', name: 'Книги', count: '30+' }, { icon: '🎯', name: 'Цели', count: '20+' }] } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Подписка', subtitle: 'Эксклюзивный контент', plans: [{ name: 'Базовый', price: '199', period: '/мес', features: ['Все посты', 'Комментарии'], highlighted: false }, { name: 'Премиум', price: '499', period: '/мес', features: ['Эксклюзив', 'Ранний доступ', 'Чат с автором'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Personal Blog', description: 'Персональный блог', links: [] } },
    ],
  },
  {
    id: 'blogger-tech',
    name: 'Tech Blogger',
    category: 'Блогеры',
    description: 'Блог о технологиях с автопостингом',
    thumbnail: '💻',
    colors: { primary: '#0f172a', secondary: '#1e293b', accent: '#22d3ee', background: '#f8fafc', text: '#0f172a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Tech Insights', subtitle: 'Обзоры технологий и гаджетов', ctaText: 'Статьи', ctaSecondary: 'Подписка' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Подписка', subtitle: 'Доступ к эксклюзивным обзорам', plans: [{ name: 'Free', price: '0', period: '/мес', features: ['Базовые статьи'], highlighted: false }, { name: 'Pro', price: '399', period: '/мес', features: ['Все обзоры', 'Видео', 'Подкасты'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Tech Blogger', description: 'Технологии', links: [] } },
    ],
  },
  {
    id: 'blogger-travel',
    name: 'Travel Diary',
    category: 'Блогеры',
    description: 'Блог о путешествиях',
    thumbnail: '✈️',
    colors: { primary: '#0891b2', secondary: '#06b6d4', accent: '#f97316', background: '#ecfeff', text: '#164e63' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Travel Diary', subtitle: 'Путешествия по миру', ctaText: 'Истории', ctaSecondary: 'Маршруты' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Travel Diary', description: 'Путешествия', links: [] } },
    ],
  },
  {
    id: 'blogger-food',
    name: 'Food Blogger',
    category: 'Блогеры',
    description: 'Фуд-блог с рецептами',
    thumbnail: '🍽️',
    colors: { primary: '#dc2626', secondary: '#ef4444', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Food Stories', subtitle: 'Вкусные истории и рецепты', ctaText: 'Рецепты', ctaSecondary: 'Подписка' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Food Blogger', description: 'Еда', links: [] } },
    ],
  },
  {
    id: 'blogger-fashion',
    name: 'Fashion Blog',
    category: 'Блогеры',
    description: 'Блог о моде и стиле',
    thumbnail: '👗',
    colors: { primary: '#be185d', secondary: '#ec4899', accent: '#fbbf24', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Style Guide', subtitle: 'Мода и тренды', ctaText: 'Луки', ctaSecondary: 'Подписка' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Fashion Blog', description: 'Мода', links: [] } },
    ],
  },
  {
    id: 'blogger-fitness',
    name: 'Fitness Coach',
    category: 'Блогеры',
    description: 'Фитнес-блог с тренировками',
    thumbnail: '💪',
    colors: { primary: '#059669', secondary: '#10b981', accent: '#f59e0b', background: '#f0fdf4', text: '#064e3b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Fit Life', subtitle: 'Тренировки и питание', ctaText: 'Программы', ctaSecondary: 'Подписка' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Fitness Coach', description: 'Фитнес', links: [] } },
    ],
  },
  {
    id: 'blogger-photo',
    name: 'Photo Blog',
    category: 'Блогеры',
    description: 'Фото-блог',
    thumbnail: '📸',
    colors: { primary: '#18181b', secondary: '#27272a', accent: '#f97316', background: '#fafafa', text: '#18181b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Photo Stories', subtitle: 'Истории в кадрах', ctaText: 'Галерея', ctaSecondary: 'Подписка' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Photo Blog', description: 'Фото', links: [] } },
    ],
  },
  {
    id: 'blogger-music',
    name: 'Music Reviews',
    category: 'Блогеры',
    description: 'Блог о музыке',
    thumbnail: '🎵',
    colors: { primary: '#7c3aed', secondary: '#a855f7', accent: '#fbbf24', background: '#faf5ff', text: '#5b21b6' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Music Vibes', subtitle: 'Обзоры и рекомендации', ctaText: 'Треки', ctaSecondary: 'Плейлисты' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Music Reviews', description: 'Музыка', links: [] } },
    ],
  },
  {
    id: 'blogger-gaming',
    name: 'Game Reviews',
    category: 'Блогеры',
    description: 'Блог об играх',
    thumbnail: '🎮',
    colors: { primary: '#7c3aed', secondary: '#a855f7', accent: '#22d3ee', background: '#faf5ff', text: '#5b21b6' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Game Zone', subtitle: 'Обзоры игр и стримы', ctaText: 'Обзоры', ctaSecondary: 'Стримы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Game Reviews', description: 'Игры', links: [] } },
    ],
  },
  {
    id: 'blogger-business',
    name: 'Business Blog',
    category: 'Блогеры',
    description: 'Блог о бизнесе',
    thumbnail: '💼',
    colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#10b981', background: '#eff6ff', text: '#1e3a8a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Business Insights', subtitle: 'Стратегии и кейсы', ctaText: 'Статьи', ctaSecondary: 'Курсы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Business Blog', description: 'Бизнес', links: [] } },
    ],
  },
  {
    id: 'blogger-marketing',
    name: 'Marketing Pro',
    category: 'Блогеры',
    description: 'Блог о маркетинге',
    thumbnail: '📈',
    colors: { primary: '#059669', secondary: '#10b981', accent: '#f59e0b', background: '#f0fdf4', text: '#064e3b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Marketing Lab', subtitle: 'Стратегии продвижения', ctaText: 'Статьи', ctaSecondary: 'Кейсы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Marketing Pro', description: 'Маркетинг', links: [] } },
    ],
  },
  {
    id: 'blogger-lifestyle',
    name: 'Lifestyle Blog',
    category: 'Блогеры',
    description: 'Лайфстайл блог',
    thumbnail: '🌟',
    colors: { primary: '#ec4899', secondary: '#f472b6', accent: '#fbbf24', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Life Stories', subtitle: 'Вдохновение каждый день', ctaText: 'Посты', ctaSecondary: 'Подписка' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Lifestyle Blog', description: 'Лайфстайл', links: [] } },
    ],
  },
  {
    id: 'blogger-beauty',
    name: 'Beauty Guru',
    category: 'Блогеры',
    description: 'Блог о красоте',
    thumbnail: '💄',
    colors: { primary: '#be185d', secondary: '#ec4899', accent: '#fbbf24', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Beauty Secrets', subtitle: 'Обзоры косметики', ctaText: 'Обзоры', ctaSecondary: 'Туториалы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Beauty Guru', description: 'Красота', links: [] } },
    ],
  },
  {
    id: 'blogger-diy',
    name: 'DIY Master',
    category: 'Блогеры',
    description: 'Блог о рукоделии',
    thumbnail: '🎨',
    colors: { primary: '#f59e0b', secondary: '#fbbf24', accent: '#ec4899', background: '#fffbeb', text: '#78350f' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'DIY Projects', subtitle: 'Мастер-классы', ctaText: 'Туториалы', ctaSecondary: 'Идеи' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'DIY Master', description: 'Рукоделие', links: [] } },
    ],
  },
  {
    id: 'blogger-parenting',
    name: 'Parenting Blog',
    category: 'Блогеры',
    description: 'Блог о воспитании детей',
    thumbnail: '👶',
    colors: { primary: '#0284c7', secondary: '#06b6d4', accent: '#f59e0b', background: '#ecfeff', text: '#164e63' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Happy Parents', subtitle: 'Советы для родителей', ctaText: 'Статьи', ctaSecondary: 'Курсы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Parenting Blog', description: 'Родителям', links: [] } },
    ],
  },
  {
    id: 'blogger-pet',
    name: 'Pet Blog',
    category: 'Блогеры',
    description: 'Блог о домашних животных',
    thumbnail: '🐾',
    colors: { primary: '#92400e', secondary: '#b45309', accent: '#16a34a', background: '#fffbeb', text: '#78350f' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Pet Love', subtitle: 'Всё о питомцах', ctaText: 'Статьи', ctaSecondary: 'Советы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Pet Blog', description: 'Питомцы', links: [] } },
    ],
  },
  {
    id: 'blogger-auto',
    name: 'Auto Blog',
    category: 'Блогеры',
    description: 'Блог об автомобилях',
    thumbnail: '🚗',
    colors: { primary: '#1c1917', secondary: '#44403c', accent: '#dc2626', background: '#fafaf9', text: '#1c1917' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Auto World', subtitle: 'Обзоры автомобилей', ctaText: 'Обзоры', ctaSecondary: 'Новости' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Auto Blog', description: 'Авто', links: [] } },
    ],
  },
  {
    id: 'blogger-realestate',
    name: 'Real Estate Blog',
    category: 'Блогеры',
    description: 'Блог о недвижимости',
    thumbnail: '🏠',
    colors: { primary: '#059669', secondary: '#10b981', accent: '#f59e0b', background: '#f0fdf4', text: '#064e3b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Property Guide', subtitle: 'Всё о недвижимости', ctaText: 'Статьи', ctaSecondary: 'Объекты' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Real Estate Blog', description: 'Недвижимость', links: [] } },
    ],
  },
  {
    id: 'blogger-finance',
    name: 'Finance Blog',
    category: 'Блогеры',
    description: 'Блог о финансах',
    thumbnail: '💰',
    colors: { primary: '#16a34a', secondary: '#22c55e', accent: '#fbbf24', background: '#f0fdf4', text: '#14532d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Money Smart', subtitle: 'Финансовая грамотность', ctaText: 'Статьи', ctaSecondary: 'Курсы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Finance Blog', description: 'Финансы', links: [] } },
    ],
  },
  {
    id: 'blogger-education',
    name: 'Education Blog',
    category: 'Блогеры',
    description: 'Блог об образовании',
    thumbnail: '🎓',
    colors: { primary: '#4f46e5', secondary: '#6366f1', accent: '#10b981', background: '#eef2ff', text: '#3730a3' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Learn Hub', subtitle: 'Образовательный контент', ctaText: 'Курсы', ctaSecondary: 'Статьи' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Education Blog', description: 'Образование', links: [] } },
    ],
  },
  {
    id: 'blogger-health',
    name: 'Health Blog',
    category: 'Блогеры',
    description: 'Блог о здоровье',
    thumbnail: '🏥',
    colors: { primary: '#0891b2', secondary: '#06b6d4', accent: '#10b981', background: '#ecfeff', text: '#164e63' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Health First', subtitle: 'Здоровый образ жизни', ctaText: 'Статьи', ctaSecondary: 'Советы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Health Blog', description: 'Здоровье', links: [] } },
    ],
  },
  {
    id: 'blogger-psychology',
    name: 'Psychology Blog',
    category: 'Блогеры',
    description: 'Блог о психологии',
    thumbnail: '🧠',
    colors: { primary: '#7c3aed', secondary: '#a855f7', accent: '#ec4899', background: '#faf5ff', text: '#5b21b6' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Mind Matters', subtitle: 'Психология и саморазвитие', ctaText: 'Статьи', ctaSecondary: 'Курсы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Psychology Blog', description: 'Психология', links: [] } },
    ],
  },
  {
    id: 'blogger-art',
    name: 'Art Blog',
    category: 'Блогеры',
    description: 'Блог об искусстве',
    thumbnail: '🎨',
    colors: { primary: '#7c2d12', secondary: '#ea580c', accent: '#0891b2', background: '#fff7ed', text: '#7c2d12' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Art World', subtitle: 'Современное искусство', ctaText: 'Галерея', ctaSecondary: 'Статьи' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Art Blog', description: 'Искусство', links: [] } },
    ],
  },
  {
    id: 'blogger-movie',
    name: 'Movie Reviews',
    category: 'Блогеры',
    description: 'Блог о кино',
    thumbnail: '🎬',
    colors: { primary: '#7f1d1d', secondary: '#b91c1c', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Cinema Club', subtitle: 'Обзоры фильмов', ctaText: 'Рецензии', ctaSecondary: 'Подборки' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Movie Reviews', description: 'Кино', links: [] } },
    ],
  },
  {
    id: 'blogger-book',
    name: 'Book Blog',
    category: 'Блогеры',
    description: 'Блог о книгах',
    thumbnail: '📚',
    colors: { primary: '#78350f', secondary: '#92400e', accent: '#f59e0b', background: '#fffbeb', text: '#78350f' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Book Worm', subtitle: 'Обзоры книг', ctaText: 'Рецензии', ctaSecondary: 'Списки' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Book Blog', description: 'Книги', links: [] } },
    ],
  },
  {
    id: 'blogger-sports',
    name: 'Sports Blog',
    category: 'Блогеры',
    description: 'Блог о спорте',
    thumbnail: '⚽',
    colors: { primary: '#16a34a', secondary: '#22c55e', accent: '#f59e0b', background: '#f0fdf4', text: '#14532d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Sports News', subtitle: 'Спортивные новости', ctaText: 'Новости', ctaSecondary: 'Аналитика' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Sports Blog', description: 'Спорт', links: [] } },
    ],
  },
  {
    id: 'blogger-science',
    name: 'Science Blog',
    category: 'Блогеры',
    description: 'Блог о науке',
    thumbnail: '🔬',
    colors: { primary: '#0c4a6e', secondary: '#0284c7', accent: '#06b6d4', background: '#f0f9ff', text: '#0c4a6e' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Science Hub', subtitle: 'Научные открытия', ctaText: 'Статьи', ctaSecondary: 'Подкасты' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Science Blog', description: 'Наука', links: [] } },
    ],
  },
  {
    id: 'blogger-news',
    name: 'News Blog',
    category: 'Блогеры',
    description: 'Новостной блог',
    thumbnail: '📰',
    colors: { primary: '#1c1917', secondary: '#44403c', accent: '#dc2626', background: '#fafaf9', text: '#1c1917' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'News Daily', subtitle: 'Ежедневные новости', ctaText: 'Читать', ctaSecondary: 'Подписка' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'News Blog', description: 'Новости', links: [] } },
    ],
  },
  {
    id: 'blogger-crypto',
    name: 'Crypto Blog',
    category: 'Блогеры',
    description: 'Блог о криптовалютах',
    thumbnail: '₿',
    colors: { primary: '#f59e0b', secondary: '#fbbf24', accent: '#000000', background: '#fffbeb', text: '#78350f' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Crypto Insights', subtitle: 'Всё о криптовалютах', ctaText: 'Аналитика', ctaSecondary: 'Новости' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Crypto Blog', description: 'Крипто', links: [] } },
    ],
  },
  {
    id: 'blogger-startup',
    name: 'Startup Blog',
    category: 'Блогеры',
    description: 'Блог о стартапах',
    thumbnail: '🚀',
    colors: { primary: '#6366f1', secondary: '#8b5cf6', accent: '#ec4899', background: '#f8fafc', text: '#0f172a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Startup Stories', subtitle: 'Истории успеха', ctaText: 'Кейсы', cтаSecondary: 'Советы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Startup Blog', description: 'Стартапы', links: [] } },
    ],
  },
];
