import { Template } from './types';

// Расширенная база шаблонов - 15+ в каждой категории
export const extendedTemplates: Template[] = [
  // === МАРКЕТПЛЕЙС (15 шаблонов) ===
  {
    id: 'ai-marketplace',
    name: 'AI Marketplace',
    category: 'Маркетплейс',
    description: 'Маркетплейс продуктов искусственного интеллекта',
    thumbnail: '🤖',
    colors: { primary: '#6366f1', secondary: '#8b5cf6', accent: '#06b6d4', background: '#0f172a', text: '#f8fafc' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AI Marketplace', subtitle: 'Откройте мир искусственного интеллекта', ctaText: 'Начать', ctaSecondary: 'Каталог' } },
      { id: 'stats', type: 'stats', editable: true, content: { items: [{ value: '2,500+', label: 'AI моделей' }, { value: '850+', label: 'Разработчиков' }, { value: '150K+', label: 'Пользователей' }, { value: '99.9%', label: 'Uptime' }] } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Тарифы', subtitle: 'Выберите план', plans: [{ name: 'Стартер', price: '0', period: '/мес', features: ['5 AI моделей', '1000 запросов/мес'], highlighted: false }, { name: 'Про', price: '49', period: '/мес', features: ['50 AI моделей', '50000 запросов/мес', 'API доступ'], highlighted: true }, { name: 'Бизнес', price: '199', period: '/мес', features: ['Безлимит', '24/7 поддержка'], highlighted: false }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AI Marketplace', description: 'Платформа AI продуктов', links: [{ title: 'Платформа', items: ['Каталог', 'API'] }] } },
    ],
  },
  {
    id: 'digital-goods',
    name: 'Digital Goods',
    category: 'Маркетплейс',
    description: 'Маркетплейс цифровых товаров',
    thumbnail: '💎',
    colors: { primary: '#7c3aed', secondary: '#a855f7', accent: '#ec4899', background: '#faf5ff', text: '#1e1b4b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Digital Goods Store', subtitle: 'Премиум цифровые товары', ctaText: 'Купить', ctaSecondary: 'Каталог' } },
      { id: 'products', type: 'products', editable: true, content: { title: 'Популярные товары', subtitle: 'Лучшие цифровые продукты', items: [{ name: 'UI Kit Pro', developer: 'DesignLab', description: 'Набор из 500+ компонентов', price: '$49', rating: 4.8, reviews: 234, tags: ['UI', 'Design'], icon: '🎨' }, { name: 'Icon Pack', developer: 'IconStudio', description: '10000+ иконок', price: '$29', rating: 4.9, reviews: 567, tags: ['Icons'], icon: '✨' }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Digital Goods', description: 'Цифровые товары', links: [] } },
    ],
  },
  {
    id: 'freelance-marketplace',
    name: 'Freelance Hub',
    category: 'Маркетплейс',
    description: 'Маркетплейс фриланс-услуг',
    thumbnail: '💼',
    colors: { primary: '#059669', secondary: '#10b981', accent: '#f59e0b', background: '#f0fdf4', text: '#064e3b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Freelance Hub', subtitle: 'Найдите лучших фрилансеров', ctaText: 'Начать', ctaSecondary: 'Каталог' } },
      { id: 'categories', type: 'categories', editable: true, content: { title: 'Категории услуг', subtitle: 'Выберите нужную', items: [{ icon: '💻', name: 'Разработка', count: '5000+' }, { icon: '🎨', name: 'Дизайн', count: '3000+' }, { icon: '✍️', name: 'Копирайтинг', count: '2000+' }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Freelance Hub', description: 'Фриланс платформа', links: [] } },
    ],
  },
  {
    id: 'nft-marketplace',
    name: 'NFT Gallery',
    category: 'Маркетплейс',
    description: 'Маркетплейс NFT и цифрового искусства',
    thumbnail: '🖼️',
    colors: { primary: '#0f172a', secondary: '#1e293b', accent: '#f43f5e', background: '#020617', text: '#f8fafc' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'NFT Gallery', subtitle: 'Коллекционируйте цифровое искусство', ctaText: 'Купить NFT', ctaSecondary: 'Коллекция' } },
      { id: 'products', type: 'products', editable: true, content: { title: 'Топ NFT', subtitle: 'Самые популярные', items: [{ name: 'Cosmic Dream #1', developer: 'ArtistX', description: 'Уникальное цифровое искусство', price: '2.5 ETH', rating: 5.0, reviews: 12, tags: ['Art', 'Rare'], icon: '🌌' }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'NFT Gallery', description: 'NFT маркетплейс', links: [] } },
    ],
  },
  {
    id: 'stock-photos',
    name: 'PhotoStock',
    category: 'Маркетплейс',
    description: 'Маркетплейс стоковых фотографий',
    thumbnail: '📸',
    colors: { primary: '#0891b2', secondary: '#06b6d4', accent: '#f97316', background: '#ecfeff', text: '#164e63' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'PhotoStock', subtitle: 'Миллионы качественных фото', ctaText: 'Найти фото', ctaSecondary: 'Категории' } },
      { id: 'categories', type: 'categories', editable: true, content: { title: 'Категории', subtitle: 'Популярные темы', items: [{ icon: '🏙️', name: 'Город', count: '50K+' }, { icon: '🌿', name: 'Природа', count: '80K+' }, { icon: '👥', name: 'Люди', count: '100K+' }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'PhotoStock', description: 'Стоковые фото', links: [] } },
    ],
  },
  {
    id: 'courses-marketplace',
    name: 'CourseHub',
    category: 'Маркетплейс',
    description: 'Маркетплейс онлайн-курсов',
    thumbnail: '🎓',
    colors: { primary: '#4f46e5', secondary: '#6366f1', accent: '#10b981', background: '#eef2ff', text: '#312e81' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'CourseHub', subtitle: 'Лучшие онлайн-курсы от экспертов', ctaText: 'Начать обучение', ctaSecondary: 'Каталог' } },
      { id: 'categories', type: 'categories', editable: true, content: { title: 'Направления', subtitle: 'Выберите курс', items: [{ icon: '💻', name: 'Программирование', count: '500+' }, { icon: '📊', name: 'Маркетинг', count: '300+' }, { icon: '🎨', name: 'Дизайн', count: '200+' }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'CourseHub', description: 'Онлайн обучение', links: [] } },
    ],
  },
  {
    id: 'music-marketplace',
    name: 'BeatStore',
    category: 'Маркетплейс',
    description: 'Маркетплейс музыки и битов',
    thumbnail: '🎵',
    colors: { primary: '#be185d', secondary: '#ec4899', accent: '#fbbf24', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'BeatStore', subtitle: 'Профессиональные биты и музыка', ctaText: 'Слушать', ctaSecondary: 'Каталог' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'BeatStore', description: 'Музыкальный маркетплейс', links: [] } },
    ],
  },
  {
    id: 'themes-marketplace',
    name: 'ThemeShop',
    category: 'Маркетплейс',
    description: 'Маркетплейс тем и шаблонов',
    thumbnail: '🎨',
    colors: { primary: '#7c2d12', secondary: '#ea580c', accent: '#16a34a', background: '#fff7ed', text: '#431407' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'ThemeShop', subtitle: 'Готовые темы для вашего сайта', ctaText: 'Выбрать тему', ctaSecondary: 'Демо' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'ThemeShop', description: 'Темы и шаблоны', links: [] } },
    ],
  },
  {
    id: 'plugins-marketplace',
    name: 'PluginHub',
    category: 'Маркетплейс',
    description: 'Маркетплейс плагинов и расширений',
    thumbnail: '🔌',
    colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#dc2626', background: '#eff6ff', text: '#1e3a8a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'PluginHub', subtitle: 'Расширения для вашего бизнеса', ctaText: 'Каталог', ctaSecondary: 'Популярные' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'PluginHub', description: 'Плагины', links: [] } },
    ],
  },
  {
    id: 'services-marketplace',
    name: 'ServiceHub',
    category: 'Маркетплейс',
    description: 'Маркетплейс услуг',
    thumbnail: '🛠️',
    colors: { primary: '#065f46', secondary: '#059669', accent: '#f59e0b', background: '#ecfdf5', text: '#064e3b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'ServiceHub', subtitle: 'Найдите исполнителя для любой задачи', ctaText: 'Найти услугу', ctaSecondary: 'Категории' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'ServiceHub', description: 'Маркетплейс услуг', links: [] } },
    ],
  },
  {
    id: 'software-marketplace',
    name: 'SoftStore',
    category: 'Маркетплейс',
    description: 'Маркетплейс программного обеспечения',
    thumbnail: '💿',
    colors: { primary: '#3730a3', secondary: '#4f46e5', accent: '#06b6d4', background: '#eef2ff', text: '#312e81' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'SoftStore', subtitle: 'Лицензионное ПО по лучшим ценам', ctaText: 'Каталог', ctaSecondary: 'Акции' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'SoftStore', description: 'Магазин ПО', links: [] } },
    ],
  },
  {
    id: 'fonts-marketplace',
    name: 'FontMarket',
    category: 'Маркетплейс',
    description: 'Маркетплейс шрифтов',
    thumbnail: '🔤',
    colors: { primary: '#581c87', secondary: '#9333ea', accent: '#f59e0b', background: '#faf5ff', text: '#3b0764' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'FontMarket', subtitle: 'Премиум шрифты для дизайнеров', ctaText: 'Каталог', ctaSecondary: 'Бесплатные' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'FontMarket', description: 'Шрифты', links: [] } },
    ],
  },
  {
    id: '3d-marketplace',
    name: '3D Assets',
    category: 'Маркетплейс',
    description: 'Маркетплейс 3D моделей',
    thumbnail: '🎮',
    colors: { primary: '#0c4a6e', secondary: '#0284c7', accent: '#f97316', background: '#f0f9ff', text: '#0c4a6e' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: '3D Assets', subtitle: '3D модели для игр и визуализации', ctaText: 'Каталог', ctaSecondary: 'Популярные' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: '3D Assets', description: '3D модели', links: [] } },
    ],
  },
  {
    id: 'video-marketplace',
    name: 'VideoStock',
    category: 'Маркетплейс',
    description: 'Маркетплейс видеоконтента',
    thumbnail: '🎬',
    colors: { primary: '#7f1d1d', secondary: '#dc2626', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'VideoStock', subtitle: 'Стоковые видео для проектов', ctaText: 'Найти видео', ctaSecondary: 'Категории' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'VideoStock', description: 'Видеоконтент', links: [] } },
    ],
  },
  {
    id: 'templates-marketplace',
    name: 'TemplateStore',
    category: 'Маркетплейс',
    description: 'Маркетплейс готовых шаблонов',
    thumbnail: '📋',
    colors: { primary: '#134e4a', secondary: '#0d9488', accent: '#f43f5e', background: '#f0fdfa', text: '#134e4a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'TemplateStore', subtitle: 'Готовые шаблоны для бизнеса', ctaText: 'Каталог', ctaSecondary: 'Новинки' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'TemplateStore', description: 'Шаблоны', links: [] } },
    ],
  },
  {
    id: 'games-marketplace',
    name: 'GameStore',
    category: 'Маркетплейс',
    description: 'Маркетплейс инди-игр',
    thumbnail: '🎮',
    colors: { primary: '#4c1d95', secondary: '#7c3aed', accent: '#22d3ee', background: '#f5f3ff', text: '#4c1d95' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'GameStore', subtitle: 'Инди-игры от независимых разработчиков', ctaText: 'Магазин', ctaSecondary: 'Новинки' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'GameStore', description: 'Игры', links: [] } },
    ],
  },

  // === ПОРТФОЛИО (15 шаблонов) ===
  {
    id: 'designer-portfolio',
    name: 'Designer Portfolio',
    category: 'Портфолио',
    description: 'Портфолио для графического дизайнера',
    thumbnail: '🎨',
    colors: { primary: '#1e293b', secondary: '#475569', accent: '#f59e0b', background: '#ffffff', text: '#1e293b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Мария Иванова', subtitle: 'Графический дизайнер с 10-летним опытом', ctaText: 'Работы', ctaSecondary: 'Контакты' } },
      { id: 'about', type: 'about', editable: true, content: { title: 'Обо мне', description: 'Создаю визуальные решения для брендов', skills: [{ name: 'Adobe Photoshop', level: 95 }, { name: 'Illustrator', level: 90 }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Мария Иванова', description: 'Дизайнер', links: [] } },
    ],
  },
  {
    id: 'developer-portfolio',
    name: 'Developer Portfolio',
    category: 'Портфолио',
    description: 'Портфолио для разработчика',
    thumbnail: '💻',
    colors: { primary: '#0f172a', secondary: '#1e293b', accent: '#22d3ee', background: '#f8fafc', text: '#0f172a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Алексей Кодов', subtitle: 'Full-Stack разработчик', ctaText: 'Проекты', ctaSecondary: 'GitHub' } },
      { id: 'projects', type: 'projects', editable: true, content: { title: 'Проекты', items: [{ title: 'E-commerce', category: 'Web', description: 'Интернет-магазин', icon: '🛒' }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Алексей Кодов', description: 'Разработчик', links: [] } },
    ],
  },
  {
    id: 'photographer-portfolio',
    name: 'Photographer',
    category: 'Портфолио',
    description: 'Портфолио фотографа',
    thumbnail: '📷',
    colors: { primary: '#18181b', secondary: '#27272a', accent: '#f97316', background: '#fafafa', text: '#18181b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Фотограф Иван', subtitle: 'Свадебная и портретная фотография', ctaText: 'Галерея', ctaSecondary: 'Записаться' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Фотограф Иван', description: 'Фотограф', links: [] } },
    ],
  },
  {
    id: 'architect-portfolio',
    name: 'Architect',
    category: 'Портфолио',
    description: 'Портфолио архитектора',
    thumbnail: '🏛️',
    colors: { primary: '#292524', secondary: '#57534e', accent: '#d97706', background: '#fafaf9', text: '#292524' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Архитектурное бюро', subtitle: 'Современная архитектура', ctaText: 'Проекты', ctaSecondary: 'О нас' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'ArchStudio', description: 'Архитектура', links: [] } },
    ],
  },
  {
    id: 'writer-portfolio',
    name: 'Writer Portfolio',
    category: 'Портфолио',
    description: 'Портфолио писателя или копирайтера',
    thumbnail: '✍️',
    colors: { primary: '#44403c', secondary: '#78716c', accent: '#84cc16', background: '#fafaf9', text: '#44403c' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Анна Слова', subtitle: 'Писатель и копирайтер', ctaText: 'Книги', ctaSecondary: 'Блог' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Анна Слова', description: 'Писатель', links: [] } },
    ],
  },
  {
    id: 'musician-portfolio',
    name: 'Musician',
    category: 'Портфолио',
    description: 'Портфолио музыканта',
    thumbnail: '🎸',
    colors: { primary: '#581c87', secondary: '#9333ea', accent: '#fbbf24', background: '#faf5ff', text: '#581c87' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'DJ Beatmaker', subtitle: 'Электронная музыка', ctaText: 'Слушать', ctaSecondary: 'Концерты' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'DJ Beatmaker', description: 'Музыкант', links: [] } },
    ],
  },
  {
    id: 'artist-portfolio',
    name: 'Artist Gallery',
    category: 'Портфолио',
    description: 'Портфолио художника',
    thumbnail: '🎨',
    colors: { primary: '#7c2d12', secondary: '#c2410c', accent: '#0891b2', background: '#fff7ed', text: '#7c2d12' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Галерея искусств', subtitle: 'Современное искусство', ctaText: 'Работы', ctaSecondary: 'Выставки' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'ArtGallery', description: 'Искусство', links: [] } },
    ],
  },
  {
    id: 'video-portfolio',
    name: 'Videographer',
    category: 'Портфолио',
    description: 'Портфолио видеографа',
    thumbnail: '🎥',
    colors: { primary: '#0c4a6e', secondary: '#0284c7', accent: '#f43f5e', background: '#f0f9ff', text: '#0c4a6e' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Видео продакшн', subtitle: 'Рекламные ролики и клипы', ctaText: 'Работы', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'VideoPro', description: 'Видео', links: [] } },
    ],
  },
  {
    id: 'model-portfolio',
    name: 'Model Portfolio',
    category: 'Портфолио',
    description: 'Портфолио модели',
    thumbnail: '💃',
    colors: { primary: '#831843', secondary: '#be185d', accent: '#fbbf24', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Model Name', subtitle: 'Fashion & Commercial', ctaText: 'Фото', ctaSecondary: 'Контакты' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Model Name', description: 'Модель', links: [] } },
    ],
  },
  {
    id: 'consultant-portfolio',
    name: 'Consultant',
    category: 'Портфолио',
    description: 'Портфолио бизнес-консультанта',
    thumbnail: '👔',
    colors: { primary: '#1e3a8a', secondary: '#1d4ed8', accent: '#10b981', background: '#eff6ff', text: '#1e3a8a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Бизнес консультант', subtitle: 'Стратегия и развитие', ctaText: 'Услуги', ctaSecondary: 'Консультация' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'ConsultPro', description: 'Консалтинг', links: [] } },
    ],
  },
  {
    id: 'coach-portfolio',
    name: 'Life Coach',
    category: 'Портфолио',
    description: 'Портфолио коуча',
    thumbnail: '🧘',
    colors: { primary: '#065f46', secondary: '#059669', accent: '#f59e0b', background: '#ecfdf5', text: '#065f46' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Лайф коуч', subtitle: 'Достигайте целей', ctaText: 'Программы', ctaSecondary: 'Записаться' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'CoachLife', description: 'Коучинг', links: [] } },
    ],
  },
  {
    id: 'teacher-portfolio',
    name: 'Teacher',
    category: 'Портфолио',
    description: 'Портфолио преподавателя',
    thumbnail: '👨‍🏫',
    colors: { primary: '#7c2d12', secondary: '#ea580c', accent: '#3b82f6', background: '#fff7ed', text: '#7c2d12' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Преподаватель', subtitle: 'Онлайн и офлайн обучение', ctaText: 'Курсы', ctaSecondary: 'Записаться' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'TeacherPro', description: 'Обучение', links: [] } },
    ],
  },
  {
    id: 'lawyer-portfolio',
    name: 'Lawyer',
    category: 'Портфолио',
    description: 'Портфолио юриста',
    thumbnail: '⚖️',
    colors: { primary: '#1c1917', secondary: '#44403c', accent: '#b91c1c', background: '#fafaf9', text: '#1c1917' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Юридические услуги', subtitle: 'Профессиональная правовая помощь', ctaText: 'Услуги', ctaSecondary: 'Консультация' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'LawFirm', description: 'Юридические услуги', links: [] } },
    ],
  },
  {
    id: 'doctor-portfolio',
    name: 'Doctor',
    category: 'Портфолио',
    description: 'Портфолио врача',
    thumbnail: '👨‍⚕️',
    colors: { primary: '#0e7490', secondary: '#06b6d4', accent: '#10b981', background: '#ecfeff', text: '#164e63' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Доктор Иванов', subtitle: 'Врач высшей категории', ctaText: 'Записаться', ctaSecondary: 'Услуги' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Dr. Ivanov', description: 'Медицина', links: [] } },
    ],
  },
  {
    id: 'chef-portfolio',
    name: 'Chef',
    category: 'Портфолио',
    description: 'Портфолио шеф-повара',
    thumbnail: '👨‍🍳',
    colors: { primary: '#78350f', secondary: '#b45309', accent: '#dc2626', background: '#fffbeb', text: '#78350f' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Шеф-повар', subtitle: 'Авторская кухня', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'ChefPro', description: 'Кулинария', links: [] } },
    ],
  },

  // === РЕСТОРАН (15 шаблонов) ===
  {
    id: 'italian-restaurant',
    name: 'La Cucina',
    category: 'Ресторан',
    description: 'Итальянский ресторан',
    thumbnail: '🍝',
    colors: { primary: '#7c2d12', secondary: '#a16207', accent: '#dc2626', background: '#fefce8', text: '#1c1917' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'La Cucina', subtitle: 'Итальянская кухня', ctaText: 'Бронь', ctaSecondary: 'Меню' } },
      { id: 'menu', type: 'menu', editable: true, content: { title: 'Меню', subtitle: 'Лучшие блюда', categories: [{ name: 'Паста', items: [{ name: 'Карбонара', price: '720 ₽', description: 'Классическая' }] }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'La Cucina', description: 'Италия', links: [] } },
    ],
  },
  {
    id: 'japanese-restaurant',
    name: 'Sakura Sushi',
    category: 'Ресторан',
    description: 'Японский ресторан',
    thumbnail: '🍣',
    colors: { primary: '#991b1b', secondary: '#dc2626', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Sakura Sushi', subtitle: 'Японская кухня', ctaText: 'Заказать', ctaSecondary: 'Меню' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Sakura', description: 'Суши', links: [] } },
    ],
  },
  {
    id: 'burger-restaurant',
    name: 'Burger House',
    category: 'Ресторан',
    description: 'Бургерная',
    thumbnail: '🍔',
    colors: { primary: '#b91c1c', secondary: '#ef4444', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Burger House', subtitle: 'Лучшие бургеры в городе', ctaText: 'Заказать', ctaSecondary: 'Меню' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Burger House', description: 'Бургеры', links: [] } },
    ],
  },
  {
    id: 'pizza-restaurant',
    name: 'Pizza Roma',
    category: 'Ресторан',
    description: 'Пиццерия',
    thumbnail: '🍕',
    colors: { primary: '#c2410c', secondary: '#ea580c', accent: '#16a34a', background: '#fff7ed', text: '#7c2d12' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Pizza Roma', subtitle: 'Настоящая итальянская пицца', ctaText: 'Заказать', ctaSecondary: 'Меню' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Pizza Roma', description: 'Пицца', links: [] } },
    ],
  },
  {
    id: 'coffee-shop',
    name: 'Coffee Lab',
    category: 'Ресторан',
    description: 'Кофейня',
    thumbnail: '☕',
    colors: { primary: '#78350f', secondary: '#92400e', accent: '#f59e0b', background: '#fffbeb', text: '#78350f' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Coffee Lab', subtitle: 'Авторский кофе', ctaText: 'Меню', ctaSecondary: 'Адрес' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Coffee Lab', description: 'Кофе', links: [] } },
    ],
  },
  {
    id: 'steakhouse',
    name: 'Steak House',
    category: 'Ресторан',
    description: 'Стейк-хаус',
    thumbnail: '🥩',
    colors: { primary: '#450a0a', secondary: '#7f1d1d', accent: '#f59e0b', background: '#fef2f2', text: '#450a0a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Steak House', subtitle: 'Премиум стейки', ctaText: 'Бронь', ctaSecondary: 'Меню' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Steak House', description: 'Стейки', links: [] } },
    ],
  },
  {
    id: 'vegan-restaurant',
    name: 'Green Garden',
    category: 'Ресторан',
    description: 'Веганский ресторан',
    thumbnail: '🥗',
    colors: { primary: '#14532d', secondary: '#16a34a', accent: '#fbbf24', background: '#f0fdf4', text: '#14532d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Green Garden', subtitle: 'Веганская кухня', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Green Garden', description: 'Веган', links: [] } },
    ],
  },
  {
    id: 'seafood-restaurant',
    name: 'Ocean Fresh',
    category: 'Ресторан',
    description: 'Ресторан морепродуктов',
    thumbnail: '🦐',
    colors: { primary: '#0c4a6e', secondary: '#0284c7', accent: '#f97316', background: '#f0f9ff', text: '#0c4a6e' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Ocean Fresh', subtitle: 'Свежие морепродукты', ctaText: 'Бронь', ctaSecondary: 'Меню' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Ocean Fresh', description: 'Морепродукты', links: [] } },
    ],
  },
  {
    id: 'bar-lounge',
    name: 'Night Bar',
    category: 'Ресторан',
    description: 'Бар и лаунж',
    thumbnail: '🍸',
    colors: { primary: '#1e1b4b', secondary: '#312e81', accent: '#fbbf24', background: '#eef2ff', text: '#1e1b4b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Night Bar', subtitle: 'Коктейли и атмосфера', ctaText: 'Меню', ctaSecondary: 'События' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Night Bar', description: 'Бар', links: [] } },
    ],
  },
  {
    id: 'bakery',
    name: 'Sweet Bakery',
    category: 'Ресторан',
    description: 'Кондитерская',
    thumbnail: '🧁',
    colors: { primary: '#831843', secondary: '#be185d', accent: '#fbbf24', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Sweet Bakery', subtitle: 'Домашняя выпечка', ctaText: 'Каталог', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Sweet Bakery', description: 'Выпечка', links: [] } },
    ],
  },
  {
    id: 'mexican-restaurant',
    name: 'El Mariachi',
    category: 'Ресторан',
    description: 'Мексиканский ресторан',
    thumbnail: '🌮',
    colors: { primary: '#b91c1c', secondary: '#dc2626', accent: '#16a34a', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'El Mariachi', subtitle: 'Мексиканская кухня', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'El Mariachi', description: 'Мексика', links: [] } },
    ],
  },
  {
    id: 'chinese-restaurant',
    name: 'Dragon Wok',
    category: 'Ресторан',
    description: 'Китайский ресторан',
    thumbnail: '🥡',
    colors: { primary: '#991b1b', secondary: '#dc2626', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Dragon Wok', subtitle: 'Китайская кухня', ctaText: 'Меню', ctaSecondary: 'Доставка' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Dragon Wok', description: 'Китай', links: [] } },
    ],
  },
  {
    id: 'indian-restaurant',
    name: 'Spice Garden',
    category: 'Ресторан',
    description: 'Индийский ресторан',
    thumbnail: '🍛',
    colors: { primary: '#c2410c', secondary: '#ea580c', accent: '#fbbf24', background: '#fff7ed', text: '#7c2d12' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Spice Garden', subtitle: 'Индийская кухня', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Spice Garden', description: 'Индия', links: [] } },
    ],
  },
  {
    id: 'dessert-cafe',
    name: 'Sweet Dreams',
    category: 'Ресторан',
    description: 'Десертное кафе',
    thumbnail: '🍰',
    colors: { primary: '#be185d', secondary: '#ec4899', accent: '#fbbf24', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Sweet Dreams', subtitle: 'Лучшие десерты', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Sweet Dreams', description: 'Десерты', links: [] } },
    ],
  },
  {
    id: 'wine-restaurant',
    name: 'Vino & Food',
    category: 'Ресторан',
    description: 'Винный ресторан',
    thumbnail: '🍷',
    colors: { primary: '#4c1d95', secondary: '#7c3aed', accent: '#f59e0b', background: '#f5f3ff', text: '#4c1d95' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Vino & Food', subtitle: 'Винная карта и кухня', ctaText: 'Бронь', ctaSecondary: 'Меню' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Vino & Food', description: 'Вино', links: [] } },
    ],
  },

  // === ФИТНЕС (15 шаблонов) ===
  {
    id: 'power-gym',
    name: 'PowerFit Gym',
    category: 'Фитнес',
    description: 'Современный фитнес-клуб',
    thumbnail: '💪',
    colors: { primary: '#059669', secondary: '#0891b2', accent: '#f97316', background: '#f0fdf4', text: '#064e3b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'PowerFit Gym', subtitle: 'Современный фитнес-клуб', ctaText: 'Записаться', ctaSecondary: 'Программы' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Абонементы', subtitle: 'Выберите формат', plans: [{ name: 'Разовое', price: '500', period: '/занятие', features: ['Одно посещение'], highlighted: false }, { name: 'Месячный', price: '3900', period: '/мес', features: ['Безлимит', 'Тренер'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'PowerFit', description: 'Фитнес', links: [] } },
    ],
  },
  {
    id: 'yoga-studio',
    name: 'Zen Yoga',
    category: 'Фитнес',
    description: 'Студия йоги',
    thumbnail: '🧘',
    colors: { primary: '#065f46', secondary: '#059669', accent: '#fbbf24', background: '#ecfdf5', text: '#065f46' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Zen Yoga', subtitle: 'Студия йоги и медитации', ctaText: 'Расписание', ctaSecondary: 'Записаться' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Zen Yoga', description: 'Йога', links: [] } },
    ],
  },
  {
    id: 'crossfit-box',
    name: 'CrossFit Box',
    category: 'Фитнес',
    description: 'Кроссфит зал',
    thumbnail: '🏋️',
    colors: { primary: '#b91c1c', secondary: '#dc2626', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'CrossFit Box', subtitle: 'Интенсивные тренировки', ctaText: 'Записаться', ctaSecondary: 'Программы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'CrossFit Box', description: 'Кроссфит', links: [] } },
    ],
  },
  {
    id: 'pilates-studio',
    name: 'Pilates Studio',
    category: 'Фитнес',
    description: 'Студия пилатеса',
    thumbnail: '🤸',
    colors: { primary: '#be185d', secondary: '#ec4899', accent: '#06b6d4', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Pilates Studio', subtitle: 'Пилатес и растяжка', ctaText: 'Расписание', ctaSecondary: 'Записаться' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Pilates Studio', description: 'Пилатес', links: [] } },
    ],
  },
  {
    id: 'boxing-gym',
    name: 'Fight Club',
    category: 'Фитнес',
    description: 'Боксёрский зал',
    thumbnail: '🥊',
    colors: { primary: '#1c1917', secondary: '#44403c', accent: '#dc2626', background: '#fafaf9', text: '#1c1917' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Fight Club', subtitle: 'Бокс и единоборства', ctaText: 'Тренировки', ctaSecondary: 'Записаться' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Fight Club', description: 'Бокс', links: [] } },
    ],
  },
  {
    id: 'swimming-pool',
    name: 'AquaSport',
    category: 'Фитнес',
    description: 'Бассейн и аквафитнес',
    thumbnail: '🏊',
    colors: { primary: '#0c4a6e', secondary: '#0284c7', accent: '#06b6d4', background: '#f0f9ff', text: '#0c4a6e' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'AquaSport', subtitle: 'Бассейн и аквафитнес', ctaText: 'Расписание', ctaSecondary: 'Цены' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'AquaSport', description: 'Бассейн', links: [] } },
    ],
  },
  {
    id: 'dance-studio',
    name: 'Dance Academy',
    category: 'Фитнес',
    description: 'Танцевальная студия',
    thumbnail: '💃',
    colors: { primary: '#7c3aed', secondary: '#a855f7', accent: '#f43f5e', background: '#faf5ff', text: '#581c87' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Dance Academy', subtitle: 'Все виды танцев', ctaText: 'Расписание', ctaSecondary: 'Записаться' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Dance Academy', description: 'Танцы', links: [] } },
    ],
  },
  {
    id: 'martial-arts',
    name: 'Martial Arts Dojo',
    category: 'Фитнес',
    description: 'Школа боевых искусств',
    thumbnail: '🥋',
    colors: { primary: '#7f1d1d', secondary: '#b91c1c', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Martial Arts Dojo', subtitle: 'Карате, дзюдо, айкидо', ctaText: 'Секции', ctaSecondary: 'Записаться' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Dojo', description: 'Единоборства', links: [] } },
    ],
  },
  {
    id: 'personal-trainer',
    name: 'Personal Trainer',
    category: 'Фитнес',
    description: 'Персональный тренер',
    thumbnail: '🏃',
    colors: { primary: '#059669', secondary: '#10b981', accent: '#f59e0b', background: '#f0fdf4', text: '#064e3b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Personal Trainer', subtitle: 'Индивидуальные тренировки', ctaText: 'Записаться', ctaSecondary: 'Программы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'PT Pro', description: 'Тренер', links: [] } },
    ],
  },
  {
    id: 'kids-fitness',
    name: 'Kids Sport',
    category: 'Фитнес',
    description: 'Детский фитнес',
    thumbnail: '👶',
    colors: { primary: '#0284c7', secondary: '#06b6d4', accent: '#f59e0b', background: '#ecfeff', text: '#164e63' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Kids Sport', subtitle: 'Фитнес для детей', ctaText: 'Секции', ctaSecondary: 'Записать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Kids Sport', description: 'Дети', links: [] } },
    ],
  },
  {
    id: 'senior-fitness',
    name: 'Active Life',
    category: 'Фитнес',
    description: 'Фитнес для пожилых',
    thumbnail: '👴',
    colors: { primary: '#475569', secondary: '#64748b', accent: '#10b981', background: '#f8fafc', text: '#1e293b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Active Life', subtitle: 'Фитнес для старшего возраста', ctaText: 'Программы', ctaSecondary: 'Записаться' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Active Life', description: 'Активное долголетие', links: [] } },
    ],
  },
  {
    id: 'online-fitness',
    name: 'FitOnline',
    category: 'Фитнес',
    description: 'Онлайн фитнес',
    thumbnail: '📱',
    colors: { primary: '#7c3aed', secondary: '#8b5cf6', accent: '#06b6d4', background: '#faf5ff', text: '#5b21b6' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'FitOnline', subtitle: 'Тренировки онлайн', ctaText: 'Начать', ctaSecondary: 'Программы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'FitOnline', description: 'Онлайн фитнес', links: [] } },
    ],
  },
  {
    id: 'nutrition-coach',
    name: 'NutritionPro',
    category: 'Фитнес',
    description: 'Нутрициолог',
    thumbnail: '🥗',
    colors: { primary: '#14532d', secondary: '#16a34a', accent: '#f59e0b', background: '#f0fdf4', text: '#14532d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'NutritionPro', subtitle: 'Правильное питание', ctaText: 'Консультация', ctaSecondary: 'Программы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'NutritionPro', description: 'Питание', links: [] } },
    ],
  },
  {
    id: 'spa-wellness',
    name: 'Spa & Wellness',
    category: 'Фитнес',
    description: 'СПА и велнес',
    thumbnail: '🧖',
    colors: { primary: '#0e7490', secondary: '#06b6d4', accent: '#fbbf24', background: '#ecfeff', text: '#164e63' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Spa & Wellness', subtitle: 'Релакс и восстановление', ctaText: 'Процедуры', ctaSecondary: 'Записаться' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Spa & Wellness', description: 'СПА', links: [] } },
    ],
  },
  {
    id: 'rehabilitation-center',
    name: 'RehabCenter',
    category: 'Фитнес',
    description: 'Реабилитационный центр',
    thumbnail: '🏥',
    colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#10b981', background: '#eff6ff', text: '#1e3a8a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'RehabCenter', subtitle: 'Восстановление и реабилитация', ctaText: 'Программы', ctaSecondary: 'Записаться' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'RehabCenter', description: 'Реабилитация', links: [] } },
    ],
  },

  // === АГЕНТСТВО (15 шаблонов) ===
  {
    id: 'digital-agency',
    name: 'Digital Wave',
    category: 'Агентство',
    description: 'Digital-агентство',
    thumbnail: '🚀',
    colors: { primary: '#1e40af', secondary: '#7c3aed', accent: '#ec4899', background: '#f8fafc', text: '#0f172a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Digital Wave', subtitle: 'Digital-агентство полного цикла', ctaText: 'Обсудить проект', ctaSecondary: 'Кейсы' } },
      { id: 'services', type: 'categories', editable: true, content: { title: 'Услуги', subtitle: 'Полный цикл', items: [{ icon: '🎨', name: 'Дизайн', count: 'от 150K ₽' }, { icon: '💻', name: 'Разработка', count: 'от 300K ₽' }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Digital Wave', description: 'Digital', links: [] } },
    ],
  },
  {
    id: 'marketing-agency',
    name: 'MarketPro',
    category: 'Агентство',
    description: 'Маркетинговое агентство',
    thumbnail: '📈',
    colors: { primary: '#059669', secondary: '#10b981', accent: '#f59e0b', background: '#f0fdf4', text: '#064e3b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'MarketPro', subtitle: 'Маркетинг и реклама', ctaText: 'Консультация', ctaSecondary: 'Услуги' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'MarketPro', description: 'Маркетинг', links: [] } },
    ],
  },
  {
    id: 'branding-agency',
    name: 'BrandStudio',
    category: 'Агентство',
    description: 'Брендинг-агентство',
    thumbnail: '🎯',
    colors: { primary: '#7c2d12', secondary: '#ea580c', accent: '#0891b2', background: '#fff7ed', text: '#7c2d12' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'BrandStudio', subtitle: 'Создание брендов', ctaText: 'Кейсы', ctaSecondary: 'Услуги' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'BrandStudio', description: 'Брендинг', links: [] } },
    ],
  },
  {
    id: 'seo-agency',
    name: 'SEO Masters',
    category: 'Агентство',
    description: 'SEO-агентство',
    thumbnail: '🔍',
    colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#10b981', background: '#eff6ff', text: '#1e3a8a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'SEO Masters', subtitle: 'Продвижение сайтов', ctaText: 'Аудит', ctaSecondary: 'Тарифы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'SEO Masters', description: 'SEO', links: [] } },
    ],
  },
  {
    id: 'smm-agency',
    name: 'SMM Pro',
    category: 'Агентство',
    description: 'SMM-агентство',
    thumbnail: '📱',
    colors: { primary: '#be185d', secondary: '#ec4899', accent: '#06b6d4', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'SMM Pro', subtitle: 'Ведение соцсетей', ctaText: 'Тарифы', ctaSecondary: 'Кейсы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'SMM Pro', description: 'SMM', links: [] } },
    ],
  },
  {
    id: 'pr-agency',
    name: 'PR Agency',
    category: 'Агентство',
    description: 'PR-агентство',
    thumbnail: '📰',
    colors: { primary: '#1c1917', secondary: '#44403c', accent: '#dc2626', background: '#fafaf9', text: '#1c1917' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'PR Agency', subtitle: 'Связи с общественностью', ctaText: 'Консультация', ctaSecondary: 'Услуги' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'PR Agency', description: 'PR', links: [] } },
    ],
  },
  {
    id: 'video-production',
    name: 'VideoPro',
    category: 'Агентство',
    description: 'Видео-продакшн',
    thumbnail: '🎬',
    colors: { primary: '#7f1d1d', secondary: '#b91c1c', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'VideoPro', subtitle: 'Видео-продакшн', ctaText: 'Портфолио', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'VideoPro', description: 'Видео', links: [] } },
    ],
  },
  {
    id: 'photo-studio',
    name: 'PhotoStudio',
    category: 'Агентство',
    description: 'Фотостудия',
    thumbnail: '📸',
    colors: { primary: '#18181b', secondary: '#3f3f46', accent: '#f59e0b', background: '#fafafa', text: '#18181b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'PhotoStudio', subtitle: 'Профессиональная фотосъёмка', ctaText: 'Записаться', ctaSecondary: 'Портфолио' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'PhotoStudio', description: 'Фото', links: [] } },
    ],
  },
  {
    id: 'event-agency',
    name: 'EventPro',
    category: 'Агентство',
    description: 'Event-агентство',
    thumbnail: '🎉',
    colors: { primary: '#7c3aed', secondary: '#a855f7', accent: '#f59e0b', background: '#faf5ff', text: '#5b21b6' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'EventPro', subtitle: 'Организация мероприятий', ctaText: 'Заказать', ctaSecondary: 'Кейсы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'EventPro', description: 'Ивенты', links: [] } },
    ],
  },
  {
    id: 'web-studio',
    name: 'WebStudio',
    category: 'Агентство',
    description: 'Веб-студия',
    thumbnail: '🌐',
    colors: { primary: '#0c4a6e', secondary: '#0284c7', accent: '#f97316', background: '#f0f9ff', text: '#0c4a6e' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'WebStudio', subtitle: 'Создание сайтов', ctaText: 'Заказать', ctaSecondary: 'Портфолио' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'WebStudio', description: 'Веб', links: [] } },
    ],
  },
  {
    id: 'mobile-dev',
    name: 'MobileDev',
    category: 'Агентство',
    description: 'Разработка мобильных приложений',
    thumbnail: '📲',
    colors: { primary: '#4f46e5', secondary: '#6366f1', accent: '#10b981', background: '#eef2ff', text: '#3730a3' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'MobileDev', subtitle: 'Мобильные приложения', ctaText: 'Заказать', ctaSecondary: 'Кейсы' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'MobileDev', description: 'Мобильная разработка', links: [] } },
    ],
  },
  {
    id: 'content-agency',
    name: 'ContentPro',
    category: 'Агентство',
    description: 'Контент-агентство',
    thumbnail: '✍️',
    colors: { primary: '#065f46', secondary: '#059669', accent: '#f59e0b', background: '#ecfdf5', text: '#064e3b' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'ContentPro', subtitle: 'Создание контента', ctaText: 'Заказать', ctaSecondary: 'Услуги' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'ContentPro', description: 'Контент', links: [] } },
    ],
  },
  {
    id: 'recruitment-agency',
    name: 'HR Agency',
    category: 'Агентство',
    description: 'Кадровое агентство',
    thumbnail: '👥',
    colors: { primary: '#1e40af', secondary: '#3b82f6', accent: '#10b981', background: '#eff6ff', text: '#1e3a8a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'HR Agency', subtitle: 'Подбор персонала', ctaText: 'Вакансии', ctaSecondary: 'Услуги' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'HR Agency', description: 'HR', links: [] } },
    ],
  },
  {
    id: 'legal-agency',
    name: 'LawFirm',
    category: 'Агентство',
    description: 'Юридическая фирма',
    thumbnail: '⚖️',
    colors: { primary: '#1c1917', secondary: '#44403c', accent: '#b91c1c', background: '#fafaf9', text: '#1c1917' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'LawFirm', subtitle: 'Юридические услуги', ctaText: 'Консультация', ctaSecondary: 'Услуги' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'LawFirm', description: 'Юриспруденция', links: [] } },
    ],
  },
  {
    id: 'consulting-agency',
    name: 'ConsultPro',
    category: 'Агентство',
    description: 'Консалтинговое агентство',
    thumbnail: '💼',
    colors: { primary: '#1e3a8a', secondary: '#1d4ed8', accent: '#10b981', background: '#eff6ff', text: '#1e3a8a' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'ConsultPro', subtitle: 'Бизнес-консалтинг', ctaText: 'Консультация', ctaSecondary: 'Услуги' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'ConsultPro', description: 'Консалтинг', links: [] } },
    ],
  },
];
