import { Template } from './types';

// Категория "Кухня" - 30 шаблонов
export const kitchenTemplates: Template[] = [
  {
    id: 'kitchen-recipe-blog',
    name: 'Recipe Blog',
    category: 'Кухня',
    description: 'Блог с рецептами и кулинарными советами',
    thumbnail: '📖',
    colors: { primary: '#dc2626', secondary: '#ef4444', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Вкусные Рецепты', subtitle: 'Лучшие рецепты на каждый день', ctaText: 'Рецепты', ctaSecondary: 'Категории' } },
      { id: 'categories', type: 'categories', editable: true, content: { title: 'Категории рецептов', subtitle: 'Выберите блюдо', items: [{ icon: '🥗', name: 'Салаты', count: '150+' }, { icon: '🍲', name: 'Супы', count: '80+' }, { icon: '🍰', name: 'Десерты', count: '200+' }] } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Подписка', subtitle: 'Доступ ко всем рецептам', plans: [{ name: 'Базовый', price: '299', period: '/мес', features: ['50 рецептов/мес', 'Базовые категории'], highlighted: false }, { name: 'Премиум', price: '799', period: '/мес', features: ['Все рецепты', 'Видео-рецепты', 'Список покупок'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Recipe Blog', description: 'Кулинарный блог', links: [] } },
    ],
  },
  {
    id: 'kitchen-cooking-school',
    name: 'Cooking School',
    category: 'Кухня',
    description: 'Онлайн-школа кулинарии',
    thumbnail: '👨‍🍳',
    colors: { primary: '#ea580c', secondary: '#f97316', accent: '#16a34a', background: '#fff7ed', text: '#7c2d12' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Школа Кулинарии', subtitle: 'Научитесь готовить как профессионал', ctaText: 'Курсы', ctaSecondary: 'О школе' } },
      { id: 'pricing', type: 'pricing', editable: true, content: { title: 'Курсы', subtitle: 'Выберите программу обучения', plans: [{ name: 'Начинающий', price: '4990', period: '', features: ['10 уроков', 'Базовые техники'], highlighted: false }, { name: 'Профи', price: '14990', period: '', features: ['50 уроков', 'Все техники', 'Сертификат'], highlighted: true }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Cooking School', description: 'Обучение кулинарии', links: [] } },
    ],
  },
  {
    id: 'kitchen-food-delivery',
    name: 'Food Delivery',
    category: 'Кухня',
    description: 'Сервис доставки еды',
    thumbnail: '🚚',
    colors: { primary: '#16a34a', secondary: '#22c55e', accent: '#f59e0b', background: '#f0fdf4', text: '#14532d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Быстрая Доставка', subtitle: 'Еда за 30 минут', ctaText: 'Заказать', ctaSecondary: 'Меню' } },
      { id: 'categories', type: 'categories', editable: true, content: { title: 'Кухни мира', subtitle: 'Выберите cuisine', items: [{ icon: '🍕', name: 'Итальянская', count: '50+ блюд' }, { icon: '🍣', name: 'Японская', count: '40+ блюд' }, { icon: '🍔', name: 'Американская', count: '30+ блюд' }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Food Delivery', description: 'Доставка еды', links: [] } },
    ],
  },
  {
    id: 'kitchen-cafe-menu',
    name: 'Cafe Menu',
    category: 'Кухня',
    description: 'Меню кафе с онлайн-заказом',
    thumbnail: '☕',
    colors: { primary: '#78350f', secondary: '#92400e', accent: '#fbbf24', background: '#fffbeb', text: '#78350f' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Уютное Кафе', subtitle: 'Кофе и выпечка', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'menu', type: 'menu', editable: true, content: { title: 'Наше меню', subtitle: 'Свежая выпечка', categories: [{ name: 'Кофе', items: [{ name: 'Капучино', price: '250 ₽', description: 'Классический' }, { name: 'Латте', price: '280 ₽', description: 'С молоком' }] }] } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Cafe Menu', description: 'Кафе', links: [] } },
    ],
  },
  {
    id: 'kitchen-baking',
    name: 'Baking Studio',
    category: 'Кухня',
    description: 'Студия выпечки и кондитерских изделий',
    thumbnail: '🧁',
    colors: { primary: '#be185d', secondary: '#ec4899', accent: '#fbbf24', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Baking Studio', subtitle: 'Домашняя выпечка на заказ', ctaText: 'Каталог', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Baking Studio', description: 'Выпечка', links: [] } },
    ],
  },
  {
    id: 'kitchen-wine',
    name: 'Wine & Dine',
    category: 'Кухня',
    description: 'Винный ресторан с кухней',
    thumbnail: '🍷',
    colors: { primary: '#7c2d12', secondary: '#a16207', accent: '#dc2626', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Wine & Dine', subtitle: 'Вино и изысканная кухня', ctaText: 'Меню', ctaSecondary: 'Бронь' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Wine & Dine', description: 'Ресторан', links: [] } },
    ],
  },
  {
    id: 'kitchen-vegan',
    name: 'Vegan Kitchen',
    category: 'Кухня',
    description: 'Веганская кухня и рецепты',
    thumbnail: '🥬',
    colors: { primary: '#16a34a', secondary: '#22c55e', accent: '#fbbf24', background: '#f0fdf4', text: '#14532d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Vegan Kitchen', subtitle: 'Здоровая веганская еда', ctaText: 'Рецепты', ctaSecondary: 'Магазин' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Vegan Kitchen', description: 'Веган', links: [] } },
    ],
  },
  {
    id: 'kitchen-bbq',
    name: 'BBQ Master',
    category: 'Кухня',
    description: 'Мастер-классы по барбекю',
    thumbnail: '🍖',
    colors: { primary: '#b91c1c', secondary: '#dc2626', accent: '#f97316', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'BBQ Master', subtitle: 'Искусство гриля и барбекю', ctaText: 'Курсы', ctaSecondary: 'Рецепты' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'BBQ Master', description: 'Барбекю', links: [] } },
    ],
  },
  {
    id: 'kitchen-sushi',
    name: 'Sushi Art',
    category: 'Кухня',
    description: 'Искусство приготовления суши',
    thumbnail: '🍣',
    colors: { primary: '#dc2626', secondary: '#ef4444', accent: '#000000', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Sushi Art', subtitle: 'Японская кухня высшего класса', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Sushi Art', description: 'Суши', links: [] } },
    ],
  },
  {
    id: 'kitchen-pizza',
    name: 'Pizza Lab',
    category: 'Кухня',
    description: 'Лаборатория пиццы',
    thumbnail: '🍕',
    colors: { primary: '#dc2626', secondary: '#ef4444', accent: '#16a34a', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Pizza Lab', subtitle: 'Авторская пицца', ctaText: 'Заказать', ctaSecondary: 'Меню' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Pizza Lab', description: 'Пицца', links: [] } },
    ],
  },
  {
    id: 'kitchen-pasta',
    name: 'Pasta House',
    category: 'Кухня',
    description: 'Домашняя паста',
    thumbnail: '🍝',
    colors: { primary: '#ea580c', secondary: '#f97316', accent: '#16a34a', background: '#fff7ed', text: '#7c2d12' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Pasta House', subtitle: 'Свежая паста каждый день', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Pasta House', description: 'Паста', links: [] } },
    ],
  },
  {
    id: 'kitchen-burger',
    name: 'Burger Lab',
    category: 'Кухня',
    description: 'Лаборатория бургеров',
    thumbnail: '🍔',
    colors: { primary: '#b91c1c', secondary: '#dc2626', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Burger Lab', subtitle: 'Лучшие бургеры в городе', ctaText: 'Заказать', ctaSecondary: 'Меню' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Burger Lab', description: 'Бургеры', links: [] } },
    ],
  },
  {
    id: 'kitchen-desserts',
    name: 'Sweet Dreams',
    category: 'Кухня',
    description: 'Мир десертов',
    thumbnail: '🍰',
    colors: { primary: '#be185d', secondary: '#ec4899', accent: '#fbbf24', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Sweet Dreams', subtitle: 'Лучшие десерты', ctaText: 'Каталог', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Sweet Dreams', description: 'Десерты', links: [] } },
    ],
  },
  {
    id: 'kitchen-cocktails',
    name: 'Cocktail Bar',
    category: 'Кухня',
    description: 'Бар коктейлей',
    thumbnail: '🍸',
    colors: { primary: '#7c3aed', secondary: '#a855f7', accent: '#fbbf24', background: '#faf5ff', text: '#5b21b6' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Cocktail Bar', subtitle: 'Авторские коктейли', ctaText: 'Меню', ctaSecondary: 'Бронь' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Cocktail Bar', description: 'Коктейли', links: [] } },
    ],
  },
  {
    id: 'kitchen-breakfast',
    name: 'Breakfast Club',
    category: 'Кухня',
    description: 'Клуб завтраков',
    thumbnail: '🥞',
    colors: { primary: '#f59e0b', secondary: '#fbbf24', accent: '#dc2626', background: '#fffbeb', text: '#78350f' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Breakfast Club', subtitle: 'Идеальное начало дня', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Breakfast Club', description: 'Завтраки', links: [] } },
    ],
  },
  {
    id: 'kitchen-seafood',
    name: 'Ocean Fresh',
    category: 'Кухня',
    description: 'Свежие морепродукты',
    thumbnail: '🦐',
    colors: { primary: '#0284c7', secondary: '#06b6d4', accent: '#f97316', background: '#ecfeff', text: '#164e63' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Ocean Fresh', subtitle: 'Морепродукты высшего качества', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Ocean Fresh', description: 'Морепродукты', links: [] } },
    ],
  },
  {
    id: 'kitchen-steak',
    name: 'Steak House',
    category: 'Кухня',
    description: 'Стейк-хаус премиум класса',
    thumbnail: '🥩',
    colors: { primary: '#7f1d1d', secondary: '#b91c1c', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Steak House', subtitle: 'Премиум стейки', ctaText: 'Меню', ctaSecondary: 'Бронь' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Steak House', description: 'Стейки', links: [] } },
    ],
  },
  {
    id: 'kitchen-organic',
    name: 'Organic Food',
    category: 'Кухня',
    description: 'Органические продукты',
    thumbnail: '🌿',
    colors: { primary: '#16a34a', secondary: '#22c55e', accent: '#f59e0b', background: '#f0fdf4', text: '#14532d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Organic Food', subtitle: 'Натуральные продукты', ctaText: 'Каталог', ctaSecondary: 'Доставка' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Organic Food', description: 'Органик', links: [] } },
    ],
  },
  {
    id: 'kitchen-spices',
    name: 'Spice World',
    category: 'Кухня',
    description: 'Мир специй и приправ',
    thumbnail: '🌶️',
    colors: { primary: '#dc2626', secondary: '#ef4444', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Spice World', subtitle: 'Специи со всего мира', ctaText: 'Каталог', ctaSecondary: 'Рецепты' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Spice World', description: 'Специи', links: [] } },
    ],
  },
  {
    id: 'kitchen-tea',
    name: 'Tea House',
    category: 'Кухня',
    description: 'Чайный дом',
    thumbnail: '🍵',
    colors: { primary: '#16a34a', secondary: '#22c55e', accent: '#f59e0b', background: '#f0fdf4', text: '#14532d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Tea House', subtitle: 'Лучший чай со всего мира', ctaText: 'Каталог', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Tea House', description: 'Чай', links: [] } },
    ],
  },
  {
    id: 'kitchen-coffee',
    name: 'Coffee Roasters',
    category: 'Кухня',
    description: 'Обжарка кофе',
    thumbnail: '☕',
    colors: { primary: '#78350f', secondary: '#92400e', accent: '#fbbf24', background: '#fffbeb', text: '#78350f' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Coffee Roasters', subtitle: 'Свежеобжаренный кофе', ctaText: 'Каталог', ctaSecondary: 'Подписка' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Coffee Roasters', description: 'Кофе', links: [] } },
    ],
  },
  {
    id: 'kitchen-chocolate',
    name: 'Chocolate Art',
    category: 'Кухня',
    description: 'Искусство шоколада',
    thumbnail: '🍫',
    colors: { primary: '#78350f', secondary: '#92400e', accent: '#fbbf24', background: '#fffbeb', text: '#78350f' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Chocolate Art', subtitle: 'Ручной шоколад', ctaText: 'Каталог', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Chocolate Art', description: 'Шоколад', links: [] } },
    ],
  },
  {
    id: 'kitchen-bread',
    name: 'Bread Bakery',
    category: 'Кухня',
    description: 'Хлебная пекарня',
    thumbnail: '🍞',
    colors: { primary: '#92400e', secondary: '#b45309', accent: '#dc2626', background: '#fffbeb', text: '#78350f' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Bread Bakery', subtitle: 'Свежий хлеб каждый день', ctaText: 'Каталог', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Bread Bakery', description: 'Хлеб', links: [] } },
    ],
  },
  {
    id: 'kitchen-cheese',
    name: 'Cheese House',
    category: 'Кухня',
    description: 'Сырный дом',
    thumbnail: '🧀',
    colors: { primary: '#f59e0b', secondary: '#fbbf24', accent: '#dc2626', background: '#fffbeb', text: '#78350f' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Cheese House', subtitle: 'Сыры со всего мира', ctaText: 'Каталог', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Cheese House', description: 'Сыры', links: [] } },
    ],
  },
  {
    id: 'kitchen-icecream',
    name: 'Ice Cream Lab',
    category: 'Кухня',
    description: 'Лаборатория мороженого',
    thumbnail: '🍦',
    colors: { primary: '#ec4899', secondary: '#f472b6', accent: '#fbbf24', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Ice Cream Lab', subtitle: 'Авторское мороженое', ctaText: 'Вкусы', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Ice Cream Lab', description: 'Мороженое', links: [] } },
    ],
  },
  {
    id: 'kitchen-noodles',
    name: 'Noodle Bar',
    category: 'Кухня',
    description: 'Бар лапши',
    thumbnail: '🍜',
    colors: { primary: '#dc2626', secondary: '#ef4444', accent: '#fbbf24', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Noodle Bar', subtitle: 'Азиатская лапша', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Noodle Bar', description: 'Лапша', links: [] } },
    ],
  },
  {
    id: 'kitchen-salads',
    name: 'Salad Bar',
    category: 'Кухня',
    description: 'Бар салатов',
    thumbnail: '🥗',
    colors: { primary: '#16a34a', secondary: '#22c55e', accent: '#f59e0b', background: '#f0fdf4', text: '#14532d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Salad Bar', subtitle: 'Свежие салаты', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Salad Bar', description: 'Салаты', links: [] } },
    ],
  },
  {
    id: 'kitchen-soups',
    name: 'Soup Kitchen',
    category: 'Кухня',
    description: 'Кухня супов',
    thumbnail: '🍲',
    colors: { primary: '#ea580c', secondary: '#f97316', accent: '#16a34a', background: '#fff7ed', text: '#7c2d12' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Soup Kitchen', subtitle: 'Домашние супы', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Soup Kitchen', description: 'Супы', links: [] } },
    ],
  },
  {
    id: 'kitchen-smoothies',
    name: 'Smoothie Bar',
    category: 'Кухня',
    description: 'Бар смузи',
    thumbnail: '🥤',
    colors: { primary: '#ec4899', secondary: '#f472b6', accent: '#16a34a', background: '#fdf2f8', text: '#831843' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Smoothie Bar', subtitle: 'Полезные смузи', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Smoothie Bar', description: 'Смузи', links: [] } },
    ],
  },
  {
    id: 'kitchen-japanese',
    name: 'Tokyo Kitchen',
    category: 'Кухня',
    description: 'Японская кухня',
    thumbnail: '🍱',
    colors: { primary: '#dc2626', secondary: '#ef4444', accent: '#000000', background: '#fef2f2', text: '#7f1d1d' },
    sections: [
      { id: 'hero', type: 'hero', editable: true, content: { title: 'Tokyo Kitchen', subtitle: 'Аутентичная японская кухня', ctaText: 'Меню', ctaSecondary: 'Заказать' } },
      { id: 'footer', type: 'footer', editable: true, content: { companyName: 'Tokyo Kitchen', description: 'Японская кухня', links: [] } },
    ],
  },
];
